<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NexPlayUninstaller</AssemblyName>
    <RootNamespace>NexPlayUninstaller</RootNamespace>
    <ApplicationIcon>..\..\NexPlay_N_final_256.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
